[build]
  command = "yarn build"
  publish = "dist"

[template.environment]
  VUE_APP_CT_PROJECT_KEY = "allbats"
  VUE_APP_CT_CLIENT_ID = "f4vv2nAgWcU-CnyVnE-RcIGaBAlkoOsC"
  VUE_APP_CT_CLIENT_SECRET = "Dvugc3HuvmmMsKiEu4PszlRU"
  VUE_APP_CT_SCOPE = "view_shopping_lists:allbats view_customers:allbats view_project_settings:allbats view_order_edits:allbats view_states:allbats view_stores:allbats view_products:allbats view_discount_codes:allbats view_types:allbats view_orders:allbats view_published_products:allbats view_payments:allbats view_messages:allbats"
  VUE_APP_CT_AUTH_HOST = "https://auth.us-central1.gcp.commercetools.com"
  VUE_APP_CT_API_HOST = "https://api.us-central1.gcp.commercetools.com"
  YARN_FLAGS = "--no-ignore-optional"

# Rule for router history mode
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
